# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeowner',
            name='password',
        ),
    ]
