# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowners', '0003_homeowner_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeowner',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
